package it.unibo.logic;

public interface Sender {

    /**
     * Sends a formation command to the drones
     * @param formation the formation generated by the model (e.g. {"program": "circleSHape", "radius":10}
     * @return true if successful
     */
    boolean sendFormation(String formation);
    
    /**
     * Connects the MQTT client to the broker
     * @return true if the connection succeeded
     */
    boolean connect();
    
    /**
     * Disconnects the MQTT client from the broker
     * @return false if something gone wrong
     */
    boolean disconnect();
    
    /**
     * Checks whether the client is connected
     * @return true if connected
     */
    boolean isConnected();
}
