package it.unibo.logic;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import dev.langchain4j.agent.tool.Tool;

public class ToolsHandler {
    private FormationProvider formationProvider;
    private Sender sender;
    private ObjectMapper objMapper = new ObjectMapper();
    private Runnable onResetMemoryCallback;

    public ToolsHandler(FormationProvider formationProvider, Sender sender) {
        this.formationProvider = formationProvider;
        this.sender = sender;
    }

    @Tool("Ottieni una stringa in formato json con tutte le formazioni disponibili per i droni")
    public String getAvailableFormations(){
        System.out.println("Reading available formations...");
        return formationProvider.getFormationsJson();
    }

    @Tool("Valida la formazione che hai creato prima di inviarla ai droni")
    public String validateFormation(String formation) {
        System.out.println("Validating formation... :\n " + formation);
        
        try {
            JsonNode json = objMapper.readTree(formation);

            return checkProgram(json);
        }
        catch (JacksonException e) {
            return "Error: the json is not valid";
        }
    }

    @Tool("Invia formazione ai droni")
    public boolean sendFormationCommand(String formation) {
        System.out.println("Sending formation... :\n" + formation);
        return sender.sendFormation(formation);
    }

    @Tool("Resetta o cancella completamente la memoria della chat attuale per ricominciare da zero una nuova conversazione")
    public String resetChatMemory() {
        System.out.println("Resetting the Agent's memory...");
        
        if (onResetMemoryCallback != null) {
            onResetMemoryCallback.run(); // Innesca il reset nell'Agente
            return "Memory succesfull resetted";
        }
        
        return "Error: impossible to reset the memory.";
    }

    /**
     * Set the function to reset the agent memory
     * @param callback Agent mothod to reset the memory
     */
    public void setOnResetMemoryCallback(Runnable callback) {
        this.onResetMemoryCallback = callback;
    }

    /**
     * It check if the given json have all the needed charateristic to be executed by the drones
     * @param jsonFormation a jsonNode which represent the Formation generated by the Ai
     * @return a string understandable by the ai, to confirm the result or report an error
     */
    private String checkProgram(JsonNode jsonFormation) {
        List<Formation> formations = formationProvider.getFormations();
        
        // Check if there a formation in the file with this name 
        Optional<Formation> f = formations.stream()
            .filter(formation -> formation.getName().equals(jsonFormation.get("program").asText()))
            .findAny();

        if (f.isEmpty()) {
            return "Error: no Formations with this program name";
        }
        
        Set<String> requiredFields = new HashSet<>(f.get().getParameters().keySet());
        requiredFields.add("program");
        Set<String> jsonFields = new HashSet<>();
        
        jsonFormation.fieldNames().forEachRemaining(jsonFields::add);
        
        // Check if the jsonFields are all the required fields
        if (!jsonFields.equals(requiredFields)) {
            Set<String> extra = new HashSet<>(jsonFields);
            extra.removeAll(requiredFields);
            
            Set<String> missing = new HashSet<>(requiredFields);
            missing.removeAll(jsonFields);
            
            if (!extra.isEmpty()) {
                return "Error: extra fields in the json, " + extra;
            }
            if (!missing.isEmpty()) {
                return "Error: missing fields in the json, " + missing;
            }
        }
        
        return "The json is VALID";
    }
}
